test = true

[sauron_config]
model_path = "/etc/feonix-models/yolov8n.onnx"
input_size = 640
dataset_name = "COCO"
fov = [93.0, 81.0]
resolution = [4090, 2160]
image_folder = "/feonix-images"

[aircraft_properties]
turn_radius = 0.0
velocity = 0.0

[[coordinates.waypoints]]
x = 0.0
y = 0.0


[[coordinates.mapping_area]]
x = 38.314816
y = -76.548947

[[coordinates.mapping_area]]
x = 38.31546
y = -76.552653

[[coordinates.mapping_area]]
x = 38.316639
y = -76.55233

[[coordinates.mapping_area]]
x = 38.316016
y = -76.5486

[[coordinates.target_area]]
x = 38.315386
y = -76.550875

[[coordinates.target_area]]
x = 38.315683
y = -76.552586

[[coordinates.target_area]]
x = 38.315895
y = -76.552519

[[coordinates.target_area]]
x = 38.315607
y = -76.5508

[commconfig]
dad_gnc_port = 5557
gnc_dad_port = 5557
dad_sauron_port = 5556
sauron_dad_port = 5556
groundstation_ip = "192.168.1.1"
flightcomputer_ip = "192.168.1.1"
